[Thu Feb 13 15:50:32.194784 2020] [wsgi:error] [pid 2267:tid 1965835312] bar
[Thu Feb 13 15:50:32.198384 2020] [wsgi:error] [pid 2267:tid 1965835312] [['non'], ['oui']]
[Thu Feb 13 15:50:32.198585 2020] [wsgi:error] [pid 2267:tid 1965835312] [['non', 'red'], ['oui', 'green']]
[Thu Feb 13 15:50:32.202015 2020] [wsgi:error] [pid 2267:tid 1965835312] [['non'], ['oui']]
[Thu Feb 13 15:50:32.202208 2020] [wsgi:error] [pid 2267:tid 1965835312] [['non', 'red'], ['oui', 'blue']]
[Thu Feb 13 15:50:32.202632 2020] [wsgi:error] [pid 2267:tid 1965835312] ----- Environnement bar -----
[Thu Feb 13 15:50:32.202714 2020] [wsgi:error] [pid 2267:tid 1965835312] ----- Lumi\xc3\xa8res -----
[Thu Feb 13 15:50:32.203010 2020] [wsgi:error] [pid 2267:tid 1965835312] nom = led_test  | pin_addr =  5  | bluetooth_addr =  be:ff:f0:00:88:11  | couleur =  000
[Thu Feb 13 15:50:32.203153 2020] [wsgi:error] [pid 2267:tid 1965835312] nom = projo_test  | pin_addr =  3
[Thu Feb 13 15:50:32.203230 2020] [wsgi:error] [pid 2267:tid 1965835312] ----- Boutons -----
[Thu Feb 13 15:50:32.203320 2020] [wsgi:error] [pid 2267:tid 1965835312] Bouton_test
[Thu Feb 13 15:50:32.203576 2020] [wsgi:error] [pid 2267:tid 1965835312] led =  led_test  | dimmeur =  50  | duree =  2  | couleur =  0xffffff
[Thu Feb 13 15:50:32.203803 2020] [wsgi:error] [pid 2267:tid 1965835312] projo =  projo_test  | dimmeur =  75  | duree =  2
[Thu Feb 13 15:50:32.204038 2020] [wsgi:error] [pid 2267:tid 1965835312] led =  led_test  | dimmeur =  100  | duree =  2  | couleur =  0xffffff
[Thu Feb 13 15:50:32.204169 2020] [wsgi:error] [pid 2267:tid 1965835312] sleep   | duree =  5
[Thu Feb 13 15:50:32.204251 2020] [wsgi:error] [pid 2267:tid 1965835312] Bouton_test2
[Thu Feb 13 15:50:32.208162 2020] [wsgi:error] [pid 2267:tid 1965835312] [remote 192.168.43.152:39550] [[], ['non', 'red'], ['non', 'red']]
[Thu Feb 13 15:50:34.672621 2020] [wsgi:error] [pid 2267:tid 1965835312] [remote 192.168.43.152:39552] coucou je fait des trucs
[Thu Feb 13 15:50:34.679166 2020] [wsgi:error] [pid 2267:tid 1891628080] Exception in thread Thread-1:
[Thu Feb 13 15:50:34.679297 2020] [wsgi:error] [pid 2267:tid 1891628080] Traceback (most recent call last):
[Thu Feb 13 15:50:34.679335 2020] [wsgi:error] [pid 2267:tid 1891628080]   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
[Thu Feb 13 15:50:34.679370 2020] [wsgi:error] [pid 2267:tid 1891628080]     self.run()
[Thu Feb 13 15:50:34.679402 2020] [wsgi:error] [pid 2267:tid 1891628080]   File "/home/pi/maison/scenario/Instruction_led.py", line 18, in run
[Thu Feb 13 15:50:34.679437 2020] [wsgi:error] [pid 2267:tid 1891628080]     dimmeur_initial = this.projecteur.dimmeur
[Thu Feb 13 15:50:34.679470 2020] [wsgi:error] [pid 2267:tid 1891628080] AttributeError: 'Instruction_led' object has no attribute 'projecteur'
[Thu Feb 13 15:50:34.679528 2020] [wsgi:error] [pid 2267:tid 1891628080] 
[Thu Feb 13 15:50:34.682484 2020] [wsgi:error] [pid 2267:tid 1881142320] Exception in thread Thread-2:
[Thu Feb 13 15:50:34.682621 2020] [wsgi:error] [pid 2267:tid 1881142320] Traceback (most recent call last):
[Thu Feb 13 15:50:34.682658 2020] [wsgi:error] [pid 2267:tid 1881142320]   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
[Thu Feb 13 15:50:34.682693 2020] [wsgi:error] [pid 2267:tid 1881142320]     self.run()
[Thu Feb 13 15:50:34.682726 2020] [wsgi:error] [pid 2267:tid 1881142320]   File "/home/pi/maison/scenario/Instruction_projecteur.py", line 17, in run
[Thu Feb 13 15:50:34.682764 2020] [wsgi:error] [pid 2267:tid 1881142320]     dimmeur_initial = this.projecteur.dimmeur
[Thu Feb 13 15:50:34.682797 2020] [wsgi:error] [pid 2267:tid 1881142320] AttributeError: 'Instruction_projecteur' object has no attribute 'projecteur'
[Thu Feb 13 15:50:34.682858 2020] [wsgi:error] [pid 2267:tid 1881142320] 
[Thu Feb 13 15:50:34.684630 2020] [wsgi:error] [pid 2267:tid 1891628080] Exception in thread Thread-3:
[Thu Feb 13 15:50:34.684728 2020] [wsgi:error] [pid 2267:tid 1891628080] Traceback (most recent call last):
[Thu Feb 13 15:50:34.684768 2020] [wsgi:error] [pid 2267:tid 1891628080]   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
[Thu Feb 13 15:50:34.684870 2020] [wsgi:error] [pid 2267:tid 1891628080]     self.run()
[Thu Feb 13 15:50:34.684904 2020] [wsgi:error] [pid 2267:tid 1891628080]   File "/home/pi/maison/scenario/Instruction_led.py", line 18, in run
[Thu Feb 13 15:50:34.684939 2020] [wsgi:error] [pid 2267:tid 1891628080]     dimmeur_initial = this.projecteur.dimmeur
[Thu Feb 13 15:50:34.684971 2020] [wsgi:error] [pid 2267:tid 1891628080] AttributeError: 'Instruction_led' object has no attribute 'projecteur'
[Thu Feb 13 15:50:34.685033 2020] [wsgi:error] [pid 2267:tid 1891628080] 
[Thu Feb 13 15:50:39.691225 2020] [wsgi:error] [pid 2267:tid 1965835312] [remote 192.168.43.152:39552] ['oui', 'red'] etat =  True
[Thu Feb 13 15:50:39.748408 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39552] [[], ['oui', 'red'], ['non', 'red']]
[Thu Feb 13 15:50:42.803655 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] coucou je fait des trucs
[Thu Feb 13 15:50:42.821365 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] [2020-02-13 15:50:42,808] ERROR in app: Exception on /Bouton_test [GET]
[Thu Feb 13 15:50:42.821503 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] Traceback (most recent call last):
[Thu Feb 13 15:50:42.821541 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/home/pi/maison/web_app/Bouton_html.py", line 37, in wrapper
[Thu Feb 13 15:50:42.821577 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     return func()
[Thu Feb 13 15:50:42.821611 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/home/pi/maison/web_app/Bouton_html.py", line 25, in bouton
[Thu Feb 13 15:50:42.821647 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     this.do()
[Thu Feb 13 15:50:42.821680 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/home/pi/maison/tree/Bouton.py", line 21, in do
[Thu Feb 13 15:50:42.821714 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     this.liste_inst.do()
[Thu Feb 13 15:50:42.821748 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/home/pi/maison/scenario/Liste_instructions.py", line 22, in do
[Thu Feb 13 15:50:42.821783 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     inst.start()
[Thu Feb 13 15:50:42.821816 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3.5/threading.py", line 840, in start
[Thu Feb 13 15:50:42.821852 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     raise RuntimeError("threads can only be started once")
[Thu Feb 13 15:50:42.821887 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] RuntimeError: threads can only be started once
[Thu Feb 13 15:50:42.821921 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] 
[Thu Feb 13 15:50:42.821953 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] During handling of the above exception, another exception occurred:
[Thu Feb 13 15:50:42.821988 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] 
[Thu Feb 13 15:50:42.822019 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] Traceback (most recent call last):
[Thu Feb 13 15:50:42.822054 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
[Thu Feb 13 15:50:42.822090 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     response = self.full_dispatch_request()
[Thu Feb 13 15:50:42.822125 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Thu Feb 13 15:50:42.822161 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     rv = self.handle_user_exception(e)
[Thu Feb 13 15:50:42.822252 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Thu Feb 13 15:50:42.822291 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     reraise(exc_type, exc_value, tb)
[Thu Feb 13 15:50:42.822325 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
[Thu Feb 13 15:50:42.822360 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     raise value
[Thu Feb 13 15:50:42.822394 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Thu Feb 13 15:50:42.822429 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     rv = self.dispatch_request()
[Thu Feb 13 15:50:42.822463 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
[Thu Feb 13 15:50:42.822499 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Feb 13 15:50:42.822534 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]   File "/home/pi/maison/web_app/Bouton_html.py", line 40, in wrapper
[Thu Feb 13 15:50:42.822568 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554]     logger.exception("Service exception: %s", e)
[Thu Feb 13 15:50:42.822610 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] NameError: name 'logger' is not defined
[Thu Feb 13 15:50:42.822758 2020] [wsgi:error] [pid 2267:tid 1932264496] [remote 192.168.43.152:39554] 
